---
services:
  grpc-cocroach-microservice:
    # image: yaninyzwitty/grpc-cocroach-microservice:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - memcached
    environment:
      - COCROACH_DB_PASSWORD
      - COCROACH_USERNAME
    env_file:
      - .env
    
  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"  
    command: ["-m", "64"] # Limit memory usage to 64MB
